name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
        
    - name: Setup Go environment
      uses: actions/setup-go@v3.0.0

    - name: Build
      run: go build -v ../../

    - name: Test
      run: go test -v ../../
